{{- if .Values.website.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gethue-website
  labels:
    deployment: gethue-website
spec:
  selector:
    matchLabels:
      pod: gethue-website
  replicas: 1
  template:
    metadata:
      labels:
        pod: gethue-website
    spec:
      containers:
      - name: gethue-website
        image: {{ .Values.image.registry }}/website:latest
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 60
          failureThreshold: 30
{{- end -}}
