{{- if and .Values.ingress.create (eq .Values.ingress.type "nginx-ssl") -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: gethue-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-website-prod
    certmanager.k8s.io/acme-challenge-type: http01
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "hue-website-ingress"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
  rules:
  - host: {{ .Values.docs.domain }}
    http:
      paths:
      - backend:
          serviceName: gethue-docs
          servicePort: 80
        path: /
  tls:
  - hosts:
    - {{ .Values.docs.domain }}
    secretName: letsencrypt-pro
{{- end -}}
