{{- if .Values.website.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: gethue-website
  labels:
    pod: gethue-website
spec:
  selector:
    pod: gethue-website
  ports:
  - name: gethue-website
    port: 9002
    targetPort: 80
  type: NodePort
{{- end -}}
